### ISSUE TITLE
Understanding Pciseq output

### ISSUE THREAD

**Issue by pakiessling** [acycliq/pciSeq#13]
Hi again,
I am doing some more tests with Pciseq and have now completed several runs.
What I would like to do is compare the Pciseq output with other segmentation & assignment outputs.
To do that I would like to construct a Cell x Gene matrix containing the spots assigned by Pciseq.

Do you have suggestion on how to accomplish that? What unit is CellGeneCount in cellData in?

Or do I need to group geneData by the assinged neighbour?

Thank you!

**Comment by acycliq** [comment]
Hi

I saw your msg, I will get back to you later today. If you have set `save_data` to `True` when you did the run, then you should have a pickle saved in the temp dir, from that you can get the cell by gene array, it is in `obj.cells.geneCount` where obj is the pickle object, 

I will come back later in anycase

**Comment by pakiessling** [comment]
Thanks.

I see that it contains one more cell then the cells dataframe. I guess there is the zero cell in there ?

**Comment by acycliq** [comment]
yes, the top row, cell with label = 0, is the background. It doest have any values here, it contains zeros only. If you want to get the  counts on the background then this is in `.cells.background_counts`. The sum of the two, ie `obj.cells.background_counts.sum() + obj.cells.geneCount.sum()` will be the total number of your spots

The cell labels are the row numbers in `.cells.geneCount`, ie the 
row number = 0 is the cell label = 0, ie the background
row number = 1 is the cell label = 1, etc

The column labels are the genes sorted alphabetically, we can get it from obj.genes.gene_panel

However those labels (lets call it pciSeq labels) might not be the same with the labels you pass in with your segmentation array from cellpose for example. Cellpose might give labels which have gaps between them like, 1,2,3,5, 10, 11, etc. 
If you want to get the mapping between cellpose and pciSeq labels then call `obj.counts_within_radius(10)` and look at the first two columns. Im cannot check right now, but I think that should work

**Comment by pakiessling** [comment]
Perfect!

Everything is set-up exactly as you are saying.
The cellpose-pciseq mapping will also come in very handy

**Comment by acycliq** [comment]
Hi 

I didnt give an answer to your question, "What unit is CellGeneCount in cellData in?", 

These are the counts of the corresponding gene in a given cell. If you are puzzled why these are not integers, the answer is because of the nature of pciSeq. This is a soft clustering algoritm and not a hard one where something either belongs to a cell or does not. Here everything comes with a probability. 

To put it in a very simplistic way, lets say we have only two cells and just one spot. If for example you think that it is equally likely the spot to "belong" to any of the two cells, then you would give 0.5 counts to the first cell and another 0.5 to the second. 
Similarly if you see for example that  a cell has lets say 1.4 counts of Npy, one way you could end up to something like that is to have two Npy spots, one assigned to the cell with 100% probability and the other spot with 40%.

A hard clustering approach is a special case of this where the assignemnt probabilities are 100%
