### ISSUE TITLE
Memory usage for MERFISH data

### ISSUE THREAD

**Issue by VPetukhov** [acycliq/pciSeq#2]
Hi Dimitris,

Thank you so much for rewriting pciSeq in python, it's such a pleasure to use now!
I was asked to benchmark Baysor against pciSeq for our revision and have ran it on MERFISH (3.7M molecules, 140 genes and ~6k cells). It worked quite well, but the memory usage was above the sky: around 670Gb RAM. Is it a realistic number or did I make something wrong?

Here is the code I used to run pciSeq:
```python
#!/usr/bin/env python

import pandas as pd
import numpy as np
from scipy.sparse import coo_matrix
import pciSeq
import scanpy as sc
import tifffile
from sys import argv
import skimage

DATA_PATH = argv[1]
OUT_PATH = argv[2]
N_SC_CELLS = 5000

# Read scRNA-seq and sample 5k cells
adata = sc.read_10x_mtx(f"{DATA_PATH}/scrna_seq")
sc_rna_df = adata.to_df().T
sc_rna_df_subs = sc_rna_df.iloc[:,np.random.choice(np.arange(sc_rna_df.shape[1], dtype=int), size=N_SC_CELLS, replace=False)]

# Read MERFISH data and prepare column names
spots = pd.read_csv(f"{DATA_PATH}/merfish_coords_adj.csv")
spots = spots[["x", "y", "gene"]].rename(columns=dict(gene="Gene"))

# Read watershed segmentation
seg_mask = tifffile.imread(f"{DATA_PATH}/dapi_merged_watershed.tif")
seg_labs = coo_matrix(skimage.measure.label(seg_mask))

# Run pciSeq
opts = {"exclude_genes": ['Blank-1', 'Blank-2', 'Blank-3', 'Blank-4', 'Blank-5', 'Krt90']}
pci_res = pciSeq.fit(spots, seg_labs, sc_rna_df_subs, opts=opts)

# Save results
pci_res[0].to_csv(f"{OUT_PATH}/cells.csv")
pci_res[1].to_csv(f"{OUT_PATH}/spots.csv")
```

**Comment by acycliq** [comment]
Hi Viktor

670GB sounds way too high! Internally there is 3-dimensional array that gets created which is `numCells-by-numGenes-by-numClasses` and is the main bottlenect when data get too big. In your case however that shouldnt be a problem. Assuming you have let's say 200 cell classes this array should consume around 1.25GB (since
`140 * 6000 * 200 * 8/ (1024**3) = 1.25` and because a `float64` consumes 8  bytes of memory).
The number of molecules, I dont think should be a big problem either
I was able to run 1.5million spots with more that 200K cells and 266genes and 72 cell classes on a 64GB RAM machine but I had downcast the 3D array I mentioned above as a float16 to reduce my memory footprint.

I can have a look if you can share your data. Your script however looks fine, I dont see anything fishy there

**Comment by VPetukhov** [comment]
Thank you! That does sound reasonable. I sent you the data over e-mail!
